fixtures:
  symlinks:
    composer: "#{source_dir}"
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
