name        'willdurand-composer'
version     '0.0.4'
summary     'This module installs Composer, a dependency manager for PHP.'
description 'This module installs Composer, a dependency manager for PHP.'
license     'MIT'
author      'William Durand'
